### ISSUE TITLE
Going to idle mode after a certain duration causes Realtime API to break

### ISSUE THREAD

**Issue by rajesh6161** [benallfree/pockethost#10]
Hey @benallfree first of all thanks for providing us pockethost for testing pb in production. But I am facing an issue everytime, while doing realtime activities. I found this might be the reason that pockethost is going to idle mode?
If I am wrong can you suggest me how to make it work.
P.S:  I am using react in client side.

**Comment by benallfree** [comment]
Hi @rajesh6161, are you running an instance from pockethost.io or are you running your own build of pockethost?

**Comment by benallfree** [comment]
Ok I see your issue at https://github.com/pocketbase/pocketbase/discussions/795.

One easy way to tell would be to increase the ttl to 5-10 minutes to see if that solves your problem. If it does, then we know that the pocketbase instance needs to stay alive while realtime processes are active.

**Comment by rajesh6161** [comment]
> 

I am running an instance from pockethost.io

**Comment by benallfree** [comment]
@rajesh6161 I have adjusted the timeout from 5 seconds to 1 hour for testing purposes. Can you please try again and report back?

**Comment by rajesh6161** [comment]
Yes sure @benallfree I will let you know once your server boots up

**Comment by benallfree** [comment]
It's up.

**Comment by rajesh6161** [comment]
Hey @benallfree it works totally fine now 🥰. It proves we have to increase the idle time.

**Comment by benallfree** [comment]
Great, I'm going to keep this issue open while we investigate options. A couple ideas I have:

1. I think there was mention of a 5 minute idle timeout in PocketBase. Maybe we could mimic that.
2. There must be a way to detect whether a user has disconnected and wouldn't receive events anyway. I can look into that.
3. For the future, I was thinking of doing a paid tier based on minutes of run time. Maybe realtime capabilities fit in this somehow too.

**Comment by rajesh6161** [comment]
Yeah that would be a great edition! for paid features.
I have deployed the app on vercel have a look into it:

https://pbrealtimeblog.vercel.app/

and even when you make it paid, please at least keep one server for free, where I can add demos/tutorials for pocketbase for other people to try 😅

**Comment by benallfree** [comment]
Good ideas! I checked out the app, that's great! Vercel+Pockethost is a good combo.

Please consider mentioning pockethost.io as a backend option in your blog readme, in case they don't want to set up a local instance. I find developing the frontend against a hosted backend makes things very easy 👼

**Comment by benallfree** [comment]
Leaving a note here that http-proxy events might be a way to detect whether a connection is still active so we don't timeout during that period. https://github.com/http-party/node-http-proxy#listening-for-proxy-events

**Comment by benallfree** [comment]
We may even push this past 1.0 since a longer timeout seems to solve the issue completely.

**Comment by benallfree** [comment]
Closing because this has been fixed.
