### ISSUE TITLE
Onboarding ux

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#102]
Current problems:

* Home page signup form dumps me on a 404 page
* I think we need to make it clearer that the instance won’t run without account verification. Maybe we can default the instance to a `frozen` status or something and/or put a big note that it won’t work. Just thinking out loud here
* This might be an issue to bring up with the core project, but on mobile Safari, the verification email is opened in an embedded browser where the user is not signed in. Verifying the token doesn’t seem to log them in. I need to research more but I think you can repro this by deleting all cookies and local storage before clicking the verification link. It took me to the dashboard with no instances showing. 

Thoughts @brewhousedigital?

**Comment by brewhousedigital** [comment]
That'd be fun! Some intro carousel that can show some fun graphics? We can include the creation widget too or let them skip to the main dashboard. 

Should also include a bug fix to add a notification to existing instances with an unverified account that it won't work without verification.

**Comment by benallfree** [comment]
Yeah and another thought, when logged in I think the home page should just be the dashboard. It's a little confusing to land back on the CTA page. 

What would the carousel be for?

**Comment by brewhousedigital** [comment]
I realize now I was thinking of something different when I read this issue lol. I opened a PR here for "Onboarding". Not sure if you even wanted this haha but it's here now if you want it.

https://github.com/benallfree/pockethost/pull/106

As for the other items:

- Homepage instance generator redirect has been fixed with the above PR
- I like that idea for the "frozen" status. I can add that to the above PR if you want or create a new one. Let me know which works best.
- Not sure the core project can fix that. It's just an annoying web view thing that phones / apps will do. Do you know if it successfully confirmed your account even if it didn't log you in?

**Comment by benallfree** [comment]
Haha yes I was waiting for that to click lol. It's okay, I like the PR you created!

> Homepage instance generator redirect has been fixed with the above PR

Nice. I changed it to a hard redirect in the mean time, but if you fixed it I'll put it back to your way.

> I like that idea for the "frozen" status. I can add that to the above PR if you want or create a new one. Let me know which works best.

Let's do a separate PR. There will be some backend work too. I'm finding it helpful to complete the backend modifications first and then hand off to you for cosmetics/ux. What do you think?

> Not sure the core project can fix that. It's just an annoying web view thing that phones / apps will do. Do you know if it successfully confirmed your account even if it didn't log you in?

We talked about it more in https://github.com/pocketbase/pocketbase/discussions/1036 and it was decided that verifying an account will NOT log them in. I think it's fine, we just need to make sure we test this path so the user is bounced to a login screen after verification if their authToken is not set.

**Comment by benallfree** [comment]
Closing in favor of new issues.

**Comment by benallfree** [comment]
#107 for "frozen" discussion
