### ISSUE TITLE
Unable to access older PocketBase instance

### ISSUE THREAD

**Issue by brewhousedigital** [benallfree/pockethost#103]
Just logged into one of my first accounts and trying to access one of the PocketBase instances gives me this screen:

Not too serious but I have some table setup on there that I forgot to copy... 😬

![image](https://user-images.githubusercontent.com/66521220/201968988-a1b9d21b-5d13-4c33-95a8-c5cd42e3ff71.png)

![image](https://user-images.githubusercontent.com/66521220/201969122-53a4d6bd-d81c-4806-af08-7c1314a80a94.png)

**Comment by benallfree** [comment]
Hmm, on it!

**Comment by benallfree** [comment]
Ok, so it's showing that account as unverified:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/1068356/201978742-b7287a3d-e4e9-4998-a003-1aed2bc3fb9e.png">

**Comment by brewhousedigital** [comment]
DUH! that'll do it. I wonder if we should include a card message talking about any legacy accounts need to verify their accounts before continuing? 

Also GitHub saves copies of comments so the account info is still there. Is any of it sensitive? If so, should we delete this issue?

**Comment by benallfree** [comment]
We can delete it. Want to open another issue to discuss how to better communicate this issue to people? It’s kind of mentioned in #102

**Comment by brewhousedigital** [comment]
Yup. ready to be deleted.
