### ISSUE TITLE
Experimenting with Wasmer and AssemblyScript for AWS Function like

### ISSUE THREAD

**Issue by Xander-Br** [benallfree/pockethost#104]
Here's the runtime but I also tested with AssemblyScript(TS-Like) and Python
https://github.com/wasmerio/wasmer-go

The only thing we need to do is embedding pocketbase api right here and it's callable in wasm

<img width="470" alt="Capture" src="https://user-images.githubusercontent.com/49765415/202440202-13af3654-ab34-46c5-813c-20b2e61979d8.PNG">

Here an example in go
https://github.com/wasmerio/wasmer-go/blob/master/examples/example_imports_function_test.go

Still need more research

**Comment by benallfree** [comment]
Stale
