### ISSUE TITLE
Uploading file larger than 1mb fails

### ISSUE THREAD

**Issue by WeatherAnchor** [benallfree/pockethost#117]
I am using Pockethost.io and all the things are working really well. I setup a collection with a file field and its maximum file size is about 50mb right now. I have tried uploading from the admin dashboard and tried uploading using POST request. But still failing to upload and giving a response of 413 Request Entity Too Large.

Here is the related issue. **https://github.com/pocketbase/pocketbase/discussions/883**

**Comment by benallfree** [comment]
moved to roadmap

**Comment by eevleevs** [comment]
Still unable to upload large files, can you please inform if the limit has been raised?

**Comment by benallfree** [comment]
@eevleevs How large are you trying to upload?

**Comment by eevleevs** [comment]
About 25 MB. I can upload it from the admin UI, but not through the JS
client.

Il mer 4 dic 2024, 10:20 Ben Allfree ***@***.***> ha scritto:
