### ISSUE TITLE
CSS breakpoint issues on dashboard

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#14]
Notice the odd wrapping behavior

https://user-images.githubusercontent.com/1068356/197326028-920d3ea0-8e51-4f4c-afc7-e4c69b731865.mp4

@brewhousedigital Want to take a look at this?

**Comment by brewhousedigital** [comment]
Sure thing!

**Comment by brewhousedigital** [comment]
@benallfree Ready for retest
