### ISSUE TITLE
Developing locally throws 500 error

### ISSUE THREAD

**Issue by TechStudent10** [benallfree/pockethost#144]
I am trying to work on the UI part of PocketHost. After cloning, installing and running the app, I get a `500: Internal Error` message every time I try looking at an instance. Keep in mind, I haven't modified any code on my end.

![image](https://user-images.githubusercontent.com/76978184/209480206-49a32377-3029-4c44-808b-2731bf7c0644.png)

**Comment by benallfree** [comment]
Fixed in master

**Comment by TechStudent10** [comment]
👍🏾
