### ISSUE TITLE
Create button shows as disabled when creating a new instance with a preferred name, but it does create the instance

### ISSUE THREAD

**Issue by cheskoxd** [benallfree/pockethost#148]
If you try to create a new instance, and then you change the name of the instance, the 'Create' button shows as disabled, and it stays as disabled, but if you click it its not showing any type of progress and stays in the same screen, BUT if you go back to the admin, it creates the instance 

Hi Ben!

**Comment by benallfree** [comment]
@cheskoxd Thank you! Seems to be a bug, I'll take a look at it.

**Comment by benallfree** [comment]
Can't repro as of 0.7.1
