### ISSUE TITLE
UI - SEO and Social Sharing

### ISSUE THREAD

**Issue by brewhousedigital** [benallfree/pockethost#17]
This task is to track and implement better SEO and Social Sharing capabilities using Open Graph.

## Design

- [x] Favicon
- [x] Open Graph Poster
- [x] Manifest Icons

## Code / `app.html`

- [x] Title Tag
- [x] Meta Description
- [x] `manifest.json`
- [x] Open Graph Tags: url, type, title, description, image
- [x] Twitter Meta Properties: card, domain, url, title, description, image

## Code / Project

- [x] Implement [`<svelte:head>`](https://svelte.dev/docs#template-syntax-svelte-head) on each page for better usability

**Comment by benallfree** [comment]
Great idea, thank you for jumping on this!

**Comment by benallfree** [comment]
Closed by #34
