### ISSUE TITLE
Frontend docs cosmetics

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#173]
For @brewhousedigital

**Comment by brewhousedigital** [comment]
Hey! Want me to just skim through it? Or do you have some specific items you'd like me to look at?

**Comment by benallfree** [comment]
yeah if you wouldn't mind, pull `master` and fire up `yarn && yarn dev:www` and navigate to `/docs`. You'll see what I mean, it's very minimal with a sidebar nav that isn't responsive or anything.

If you have any ideas or run into any problems please let me know!

You might also browse to `/faq`, that one just got done too. 🚀

**Comment by AmmarR0118** [comment]
i think i have to fix the header and the sidebar. right?

**Comment by AmmarR0118** [comment]
@benallfree can i change the header also and make it someting like pocketbase.io?
