### ISSUE TITLE
Storage files are not accessible

### ISSUE THREAD

**Issue by WeatherAnchor** [benallfree/pockethost#194]
I connected to my pockethost instances using the ftp access. I tried to look inside the `pb_data/storage` folder but couldn't. It says: `This location could not be displayed. Sorry, could not display all the contents of "storage": Operation failed`. I think this may be related to this issue: https://github.com/benallfree/pockethost/discussions/186

**Comment by benallfree** [comment]
Yes, it is the same issue. Thanks for creating a ticket. 

I’ll fix this asap, or if someone wants to make a PR please do.

**Comment by benallfree** [comment]
Fixed in 0.7.1 and live now.
