### ISSUE TITLE
New app stuck on starting up

### ISSUE THREAD

**Issue by brewhousedigital** [benallfree/pockethost#2]
Hello! Wanted to try out Pockethost, so I created an account and created a new app. For the last few hours it's been stuck on this view:

The domain is incalculable-death.pockethost.io

![image](https://user-images.githubusercontent.com/66521220/195243660-ea521f8a-5850-487e-9073-e9db606af4f4.png)

![image](https://user-images.githubusercontent.com/66521220/195243676-b51967c7-cae4-4617-9939-de5bd976ec34.png)

**Comment by benallfree** [comment]
Thanks for the report! Someone else reported this too and I confirmed it.

Working on the issue now, and I'll update this ticket as I have more info.

**Comment by benallfree** [comment]
Fixed 👍
