### ISSUE TITLE
Undefined in dashboard/app

### ISSUE THREAD

**Issue by Zarvhos** [benallfree/pockethost#246]
### Discussed in https://github.com/benallfree/pockethost/discussions/245

<div type='discussions-op-text'>

<sup>Originally posted by **Zarvhos** June 27, 2023</sup>
Dear PocketHost Team,

I hope this message finds you well. I wanted to inform you about a minor issue I encountered while using PocketHost. Instead of being shown japanime-dev.pockethost.io, I am currently seeing undefined.pockethost.io. I believe there might be a technical glitch causing this discrepancy.

Image : 
<img width="649" alt="image" src="https://github.com/benallfree/pockethost/assets/61838403/c2027243-11b1-4b2a-a35d-18eb43bb6a5a">

I edited the the app name instantly after creating the instance, it might be coming from it ?

</div>

**Comment by benallfree** [comment]
Thanks for this report! If you have time to send a PR, I would appreciate it.

**Comment by benallfree** [comment]
Fixed in 0.8.2
