### ISSUE TITLE
Fade is not defined

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#30]
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/1068356/197757418-6a76bf18-f86d-452f-9f3b-6ca7a2061fb2.png">

@brewhousedigital mind taking a peek at this?

**Comment by brewhousedigital** [comment]
Checking this now

**Comment by brewhousedigital** [comment]
@benallfree That's really odd. On `dashboard/+page.js`, on line two, there is this import:

```js
import { fade } from 'svelte/transition'
```

That should be all it needs to render. I just logged into an existing account and didn't get that error on the dashboard, so I made a new account and was able to successfully navigate to the dashboard without the error. Can you confirm that the import is in your code?

**Comment by benallfree** [comment]
Fixed in https://github.com/benallfree/pockethost/commit/a149df0d583a8f43b1a7422ba849f911e90fe74b
