### ISSUE TITLE
Nav bar does not change on login, dashboard does not load on login

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#31]
When doing a fresh login, the dashboard does not load apps and the navbar doesn't change.

@brewhousedigital I'm taking a peek at this unless you have immediate ideas.

**Comment by brewhousedigital** [comment]
My only guess is the global store isn't updating. Since we moved from a hard refresh to using the sveltekit router. Is there a way to make the `isLoggedIn()` reactive?

**Comment by benallfree** [comment]
This seems to help in NavBar:

```ts
  let _isLoggedIn = isLoggedIn()
  onMount(() => {
    _isLoggedIn = isLoggedIn()
    const unsub = onAuthChange(() => {
      console.log('auth changed')
      _isLoggedIn = isLoggedIn()
    })
    onDestroy(unsub)
  })
```

But then it creates an oddity where the dashboard won't populate upon subsequent navigation back to it.
https://user-images.githubusercontent.com/1068356/197836672-fb464750-8c0b-40a4-8949-5036af2e4809.mp4

**Comment by benallfree** [comment]
Ok this has been fixed in https://github.com/benallfree/pockethost/commit/a149df0d583a8f43b1a7422ba849f911e90fe74b

**Comment by brewhousedigital** [comment]
A slightly less secure version of this would be to use a global store to save the token + user information in, so that the entire app updates as soon as the store changes. Thoughts? This way we wouldn't have to worry about onMount, and destroying subscriptions and stuff

```js
// store.js
const globalUserData = writable({});
const isLoggedIn = writable(false);

globalUserData.subscribe(value => {
	isLoggedIn.set(!!value?.user) 
});


// database.js
const response = await authViaEmail(email, password)
globalUserData.set(response)
```

```svelte
{#if isLoggedIn}
   Reactive content goes here...
{/if}
```

**Comment by benallfree** [comment]
Yeah something like that would work. I'm not super familiar with svelte stores, but that looks similar to a global React store which is normally how I would do it

```ts
const MyComponent = ()=>{

   const isLoggedIn = useIsLoggedIn()
   ... render ...
}
```

**Comment by brewhousedigital** [comment]
Let me know if you want me to swap it out! I can write out some docs for it too.

**Comment by benallfree** [comment]
It’s working for now but if you’d like to take a shot at something better go right ahead! I am so glad to have someone collaborating!
