### ISSUE TITLE
Feature: show Dart and REST samples on details page

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#33]
@brewhousedigital This is an all-frontend idea, no backend coding needed.

Check out how Stripe does their API samples https://stripe.com/docs/api

I think PocketBase supports REST, Dart, and JavaScript as the three client SDK's. It would be cool to have a widget like Stripe does that swaps code samples based on preferred SDK. And the SDK selection would be sticky in a cookie.

https://user-images.githubusercontent.com/1068356/197877848-be8aa5bf-bb4a-4d2e-8e48-6431f79184af.mp4

**Comment by brewhousedigital** [comment]
I love it! I'll start on this next. What kind of documentation would you like to include for the site? The Pocketbase system has a pretty robust API Preview system right?

**Comment by benallfree** [comment]
For docs I’d say we link to the official docs for REST, Dart, and JS. All I’m really looking for is a copypasta stub to get them started. 

For REST it would be a bash curl call, maybe like a login call or something. 

For JS it would be what we already show

For Dart it would be whatever that initialization looks like.

**Comment by benallfree** [comment]
I think, along with this, I'd like to add PocketHost CLI samples that include:

* creating a new TS/JS project
* creating an account / logging in
* uploading cloud func bundle

**Comment by benallfree** [comment]
moving to roadmap
