### ISSUE TITLE
FAQ page?

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#37]
Thoughts on whether this is needed? So far nobody is asking anything. 

@brewhousedigital

**Comment by brewhousedigital** [comment]
Possible questions:

- What happens when I reach my minutes / rate / something
- How many instances can I create
- Can I import data from my local into pockethost
- Can I export my pockethost data

**Comment by benallfree** [comment]
* What happens when I want to host my instance on my own? (aka, how do I migrate away from pockethost.io?)
* What versions of PocketBase do you support?
* How do I upgrade to the latest PocketBase version?
* How does outgoing email work?
* How does S3 storage work?
* How often does my data get backed up?

**Comment by shaparder** [comment]
Hi @benallfree @brewhousedigital,

I made a quick mockup of an FAQ section with toggle buttons. Here's what it looks like so far:

![faq-pockethost](https://user-images.githubusercontent.com/44458369/212791123-85590d63-b3b8-4a35-b5a6-ae57a7466560.png)

Any thoughts ?

Once I have some feedback and a definitive list of questions/answers I'll open a PR ! :)

All the best

**Comment by benallfree** [comment]
@shaparder This is amazing!! Thank you so much.

Check out https://pockethost.io/docs. If you pull from `master` and run the frontend, you'll see a new `docs` button up top that I'm working on here https://github.com/benallfree/pockethost/tree/master/packages/pockethost.io/src/routes/docs. 

I'm thinking your talents could best be leveraged by working on docs ux. The FAQ could go in there as a doc page. What do you think?

**Comment by shaparder** [comment]
@benallfree thanks for the kind words, even tho it ain't much yet !

I've seen the docs, would you rather have the FAQ there ? I was thinking we could keep a short FAQ for the general questions regarding the most important "should I use pockethost" type of questions in the homepage and have an extended FAQ in the docs ?

What do you prefer ?

**Comment by benallfree** [comment]
@shaparder I think I’d like to throw it in the docs section and perhaps we can make a little widget to display it from elsewhere too. Or add another top nav link. But definitely keep and maintain it with the rest of the docs.

**Comment by brewhousedigital** [comment]
@shaparder  If you set it up as a component, it'll make it easy to move it around

**Comment by shaparder** [comment]
@benallfree @brewhousedigital it is set up as a component ! I'll open a PR so we can review the code there

**Comment by benallfree** [comment]
Closed by #170
