### ISSUE TITLE
New logo?

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#39]
What about a logo that is just stacked boxes like this? 

![image](https://user-images.githubusercontent.com/1068356/198156579-65c7f68b-f33d-4c35-841d-33e0d7b9d345.png)

@brewhousedigital

**Comment by brewhousedigital** [comment]
I can play around with a few variations and post some screenshots here to see how it looks!

**Comment by benallfree** [comment]
Sorry just to be clearer, I'm thinking of a square version maybe even without letters that can be used as a favicon

**Comment by brewhousedigital** [comment]
## Box:

![image](https://user-images.githubusercontent.com/66521220/198182899-86b5f1b6-c710-4eb3-8488-8d5efc962b90.png)

## Large Box with Text:

![image](https://user-images.githubusercontent.com/66521220/198183184-708c9339-8876-4ede-967a-92e4838cf339.png)


## Small Box with Text:

![image](https://user-images.githubusercontent.com/66521220/198183226-e93ad909-5fcf-4234-bdd0-cbb53de7b37d.png)


## P.S.

I'm not much of a designer for stuff like logos lol but I'll try my best!

**Comment by benallfree** [comment]
These are really cool!

I'm thinking there is something essential in this...

<img width="130" alt="image" src="https://user-images.githubusercontent.com/1068356/198185792-922e2814-62f5-4c48-9289-c9ce833973a3.png">

I'll play with a few ideas too.

**Comment by benallfree** [comment]
Let's hold til after 1.0

**Comment by benallfree** [comment]
moved to roadmap
