### ISSUE TITLE
Verified accounts

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#40]
Right now, we don't verify email addresses. But we really should not let users start instances until their email is verified.

On the frontend, it should work like this:
* Create account
* Send out verification
* Post alert in UI if account is not verified, offer to resend verification

On the backend, it should work like this:
* Request comes in
* Look up owner
* Check verification status
* If owner is not verified, reject with a 403 Forbidden error

@brewhousedigital want to collab on this?

**Comment by brewhousedigital** [comment]
Yup! Sounds easy enough! This will be super easy if I switch over to the Svelte Store for session storage. I can query `userData.user.verified` and it returns a boolean.

**Comment by benallfree** [comment]
@brewhousedigital Sure, what if you post a PR for the frontend part and then I'll extend it with the daemon updates?

**Comment by benallfree** [comment]
Closed by #45
