### ISSUE TITLE
Redo subdomain naming strategy

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#42]
@brewhousedigital suggested  in #35 `name-name-number` rather than just `name-name`.

Since every instance gets a unique ID, I think the backend should always answer on that subdomain:

`ctg834u9gc.pockethost.io`

Then I think it's still valuable for users to be allowed to pick a globally-unique name if they want to:

`foo.pockethost.io`

That, along with #25 support, will create a nice tidy solution.

If they want to rename an instance, they can do that because metrics are linked to the uuid and not the subdomain name.

Proposed frontend changes:
* Name: `/[A-Za-z-]/` max 50 chars
* Name must be globally unique
* Name can be changed at any time
* Name CANNOT match any instance uuid

Proposed daemon changes:
* Recognize both uuids and names when resolving instance requests

**Comment by brewhousedigital** [comment]
Sounds like the user would still create their random `word-word` but in the backend we're saving `word-word-uuid`? That way, they could create a custom name like "brewhouse.pockethost.io" but in the backend it would be `brewhouse-109384.pockethost.io"? 

Or do we need to differentiate a custom name vs a generated name?

**Comment by benallfree** [comment]
@brewhousedigital Actually I think `word-word.pockethost.io` is still okay, and requiring `word-word` to be globally unique is okay too. They can always go `word-word-2` if they really are dying to have that naming. Or associate a custom domain (probably a paid level for that). Since every record in a collection has an `id` field, doing `<id>.pockethost.io` is a third way they could access their instance. But we can allow them to change `word-word` as long as it doesn't conflict with anyone else's use. Metrics will be tracked based on the `id` field anyway, so `word-word` is just decorative.

**Comment by brewhousedigital** [comment]
Makes sense! 

Do you have plans to create an API that can take in a parameter like `/api/instances/verify-name?name=brewhouse`  that we can use to receive a boolean back?

Do you think we'll need additional security on the Go side, perhaps by using `OnRecordBeforeCreateRequest` or `OnModelBeforeCreate` (not sure the difference), just incase someone tries to hit the API directly? or would setting the name field to be `unique` suffice? probably just unique right? 

Now that I type all that out, perhaps we don't need that verify-name API. If the table as a whole will just return a 400, we can read the error response and then tell the user that the name was already chosen and they need to choose something else.

**Comment by benallfree** [comment]
> we can read the error response and then tell the user that the name was already chosen and they need to choose something else

Exactly, I think that's what it does now anyway.

I'm setting this for a later milestone, but I definitely would like it for v1.

**Comment by benallfree** [comment]
moved to roadmap
