### ISSUE TITLE
Max instances per account?

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#43]
Open to discussion, after #21

**Comment by rajesh6161** [comment]
According to my use case and experience after using PockeBase and pockethost.io:
Free Tier: Only one,
Front Pocket: One
Back Pocket: two instances

**Comment by benallfree** [comment]
@rajesh6161 Firebase lets users create any number of projects. But maybe eventually we will have both instance limits and overall account limits, like not using more than 100 minutes (or 200 minutes) across ALL account instances on the free tier. And then you can upgrade certain instances to not count against that free tier limit. Tagging #44 here because I think this is an important idea!

**Comment by brewhousedigital** [comment]
Not sure if this is possible, but another platform, Backendless, has a "free" tier sort of that's just rate limited, where you pay a single flat fee of $50, and then you essentially get the rate-limited instance indefinitely. That was always nice for me since I didn't have to pay for multiple monthly instances.

**Comment by benallfree** [comment]
@brewhousedigital Yeah I'm thinking along those lines too, some kind of limited free tier that works across all instances in a given account. Maybe it does make more sense to bill per-account rather than per-instance. So you can buy 1000 minutes and it gets spread across whatever projects you have. If you want to isolate a specific project, you can always create a 2nd account for it (rare).

**Comment by benallfree** [comment]
moved to roadmap
