### ISSUE TITLE
Cookie warning thing?

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#50]
Do we need that cookie compliance pop up thing that everyone is doing?

@brewhousedigital

**Comment by brewhousedigital** [comment]
Probably. Good news is we aren't (currently) using any analytics cookies so creating a little banner saying we only use necessary cookies should suffice for California and EU requirements. 

Need to figure out what to do if they say no to cookies. May need to block the login/register page and re-prompt them to accept the cookies before continuing. 

Should be easy to do with a single svelte store

**Comment by brewhousedigital** [comment]
@benallfree we may not need this:

> No need for cookie consent when using localstorage: A site only needs to ask for cookie consent for cookies that are not “strictly necessary cookies” (learn more about it here). Session cookies count as strictly necessary and hence a user cannot deny their usage.

https://supertokens.com/blog/cookies-vs-localstorage-for-sessions-everything-you-need-to-know#:~:text=No%20need%20for%20cookie%20consent,user%20cannot%20deny%20their%20usage.

**Comment by benallfree** [comment]
Ok, so the only cookies we use are session. `theme` and `pb_auth`. I would consider both of those 'strictly necessary' for site functionality. Without them, dark mode won't work and SSR won't work. 

Can we close this ticket then?

**Comment by brewhousedigital** [comment]
Yup. We can revisit if we expand to include analytics or other optional cookies.
