### ISSUE TITLE
Missing nav on local

### ISSUE THREAD

**Issue by brewhousedigital** [benallfree/pockethost#54]
I started work on #36 but once I pulled from master, my navigation is blank now except for the non-auth links. I cleared cache but no good. Was there anything I needed to do locally to get things working with the new authcheck?

![image](https://user-images.githubusercontent.com/66521220/199388538-243b53d2-aad9-4419-b077-2dd233dbbb1d.png)

**Comment by benallfree** [comment]
Ah, I kind of overlooked this. I think I should deploy the latest stuff to the live site, then the SSR will start working correctly.

Give me a few.

**Comment by benallfree** [comment]
Ok, this should be fixed. `yarn dev` from localhost should work now.

**Comment by benallfree** [comment]
Closing as fixed on 0.4.0
