### ISSUE TITLE
Platform + version cosmetics

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#56]
With 0.4.0, we have the concept of platform names and versions within that platform. This is to group PocketBase versions by compatibility. For example, every version in the `ermine` group will run interchangeably. Just bug foxes. But the `lollipop` platform requires db upgrades and will not run ermine code or SDKs.

So, breaking changes means it's important to tell the users which version they're running.

The platform name is always the a literal platform name, but the version can either be a specific version or `latest` to make pockethost select the latest version in that platform group. 

It would be great if all of this were explained better and more intuitive. I've stubbed out the basics, but I'm curious if others have feedback about how this concept should be presented.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/1068356/199567307-506a9891-64ba-49bb-af2e-40a03a9b45da.png">

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1068356/199567426-9625636e-786d-424a-904a-5e2b71a4d244.png">

@brewhousedigital want to take a shot at this?

**Comment by brewhousedigital** [comment]
Combined this with #83
