### ISSUE TITLE
Local EACCES Bug

### ISSUE THREAD

**Issue by henryholtgeerts** [benallfree/pockethost#6]
Hello!

Trying to run pockethost locally (interested in contributing!) but hitting a wall getting going. I'm not 100% familiar with Docker, so there's a good chance this error has a quick fix, thought I'd ask here.

When I run docker compose up, everything runs smooth but pockethost-central fails to initiate correctly:
```
pbproxy  | pockethost-central had error Error: spawn /mount/pocketbase/bin/pocketbase EACCES
```

This leads to endless polling of the 'central' pb instance further along:
```
pbproxy  | Trying to connect to instance http://127.0.0.1:8090 
pbproxy  | Could not connect to http://127.0.0.1:8090
```

Tried some suggestions I could find online re: permissions & docker compose but, like I said, sorta out of my depth & interested if you can point me in the right direction. 

Thanks!

**Comment by henryholtgeerts** [comment]
Seems like the build script in `packages/pocketbase` builds to `pocketbase/dist/pocketbase`, and docker-compose is just pointing toward `pocketbase/pocketbase` which is an empty dir?

**Comment by benallfree** [comment]
Hi @henryholtgeerts thanks for the report and thank you so much for considering collaboration. It's really awesome to see people show up for this. 

I just updated https://github.com/benallfree/pockethost/blob/master/development.md with more details. Please take a look and let me know if you still are stuck.

Are you a frontend guy? If so, @brewhousedigital is doing some Svelte mods https://github.com/benallfree/pockethost/pull/5. I would invite you to sync with us on that PR if you are looking for that.

Or are you really meaning to dive into Dockerland, we can talk here.

All help is cherished and desired :)

**Comment by henryholtgeerts** [comment]
@benallfree I'm more familiar w/ frontend but really interested in learning more docker/backend stuff! This project seems exciting both b/c I like pocketbase & since it seems like a little enough codebase for me wrap my head around how it spins up instances.

Thanks for the improved dev readme!!

**Comment by henryholtgeerts** [comment]
I'm gonna close this issue, and pick up on discussions.
