### ISSUE TITLE
Is it possible to turn the Github announcements feed into a blog?

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#62]

**Comment by brewhousedigital** [comment]
I looked through the Github API and found this: https://docs.github.com/en/rest/teams/discussions#list-discussions

I didn't see any kind of category filtering though which I thought was odd. Maybe in the response we'll be able to see what category the posts are in, and filter by "Announcements" then render the info inside a `/[blog-post]/+page.svelte` file?

**Comment by benallfree** [comment]
Interesting, thanks for the research. It looks like that is for teams only, so I've marked this issue as being on hold for now.

**Comment by brewhousedigital** [comment]
An alternative would be adding a new blog directory and using Markdown to write the posts. Then you could copy and paste them into the Github Annoucements page (or vice versa). That way the formatting would be the same, but they wouldn't technically be in sync.

**Comment by benallfree** [comment]
moved to roadmap
