### ISSUE TITLE
Improve backend dev experience by programatically creating first admin user

### ISSUE THREAD

**Issue by henryholtgeerts** [benallfree/pockethost#7]
One hiccup in the backend dev experience is the need to manually create an admin user when spawning a fresh a pockethost-central db. Setting the first admin's credentials programmatically could alleviate this part of the process and help to make working on Pockethost a little closer to the simple experience that appeals to folks who choose to work with Pocketbase.

Here's a relevant discussion: https://github.com/pocketbase/pocketbase/discussions/793

**Comment by benallfree** [comment]
Want to take a shot at this?

As a stopgap, I added a warning about that if it's unable to log in using the `.env` credentials.

**Comment by henryholtgeerts** [comment]
Happy to! I'll take a look at it today or tomorrow. For simplicity I'll keep a branch just for this improvement, and when it's working it could be brought into main and your docker branch.

**Comment by benallfree** [comment]
Perfect, feel welcome to open a PR when you have something :)

**Comment by benallfree** [comment]
moved to roadmap
